'use strict';

/* Standalone visual-QA fixtures. They render the dashboard's real team
 * dispatcher with the same bounded producer-shaped data used by the regression
 * test, then retain the live stylesheet and top-bar/sidebar/page hierarchy.
 * Serve backend/web as the HTTP root so /fonts and /scout-wordmark.svg resolve. */
const fs = require('node:fs');
const path = require('node:path');
const TEAM_AVERAGES = require('../../lib/team-averages');

const WEB = path.join(__dirname, '..', '..', 'web');
const HTML = fs.readFileSync(path.join(WEB, 'dashboard.html'), 'utf8');
const STYLE = /<style[^>]*>([\s\S]*?)<\/style>/.exec(HTML)[1];
const RAW_SCRIPT = [...HTML.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)]
  .map((match) => match[1]).sort((a, b) => b.length - a.length)[0];
const SCRIPT = RAW_SCRIPT.replace(/\n\s*init\(\);\s*$/, '\n');
const CHROME_START = HTML.lastIndexOf('<nav class="top-bar">');
const CHROME = HTML.slice(CHROME_START, HTML.indexOf('<div id="content">', CHROME_START));

const REP = { user_id: 'rep-1', display_name: 'Ava', calls_analyzed: 24, active: true, prospect_close_rate: 25, prospect_close_wins: 6, prospect_close_total: 24, obj_handle_rate: 42, obj_handled: 10, obj_total: 24, avg_call_time: 41, avg_score: 72, sections: { intro: 75, discovery: 69, pitch: 71, objection: 66, close: 78 }, weakest_section: { section: 'objection', score: 66 }, weakest_objection: null };
const PERFORMANCE_REPS = [REP, { ...REP, user_id: 'rep-2', display_name: 'Drew', prospect_close_rate: 31, prospect_close_wins: 8, obj_handle_rate: 55, obj_handled: 13, avg_call_time: 38, avg_score: 79, sections: { intro: 81, discovery: 76, pitch: 80, objection: 72, close: 84 } }, { ...REP, user_id: 'rep-3', display_name: 'Morgan', prospect_close_rate: 18, prospect_close_wins: 4, obj_handle_rate: 29, obj_handled: 7, avg_call_time: 48, avg_score: 63, sections: { intro: 67, discovery: 62, pitch: 65, objection: 55, close: 68 } }];
const COACHING_REP = { user_id: 'rep-1', name: 'Ava', calls: 1, recent_calls: [], period_summary: { status: 'ready', from: '2026-09-01T00:00:00.000Z', to: '2026-09-30T23:59:59.999Z', patterns: [], coaching: { state: 'item', label: 'Close', move: 'asking for the sale', calls: 1, recurring: false, example: { call_id: 'call-verified', call_date: '2026-09-12T10:00:00.000Z', prospect_name: 'Morgan', outcome: 'follow_up', source: 'fathom', observation: 'The prospect asked for time and the call ended without a confirmed next step.', recommendation: 'Ask for a specific next step before ending the call.', clip_url: 'https://fathom.video/calls/verified?t=120', evidence: [{ speaker: 'PROSPECT', quote: 'I need a day to think about this.', timestamp_seconds: 120 }, { speaker: 'CLOSER', quote: 'Of course, reach out when you are ready.', timestamp_seconds: 126 }] } } } };
const TEAM_RECS = { available: true, working: [{ claim: 'Ava made the prospect feel heard before presenting the next step.', data: 'The prospect stayed engaged after the summary.', quote: 'That makes sense to me.', rep: 'Ava', spoke: 'prospect', call_id: 'call-verified', highlight_id: 'highlight-1' }], improve: [{ claim: 'Make the next step specific when a prospect needs time.', data: 'The call ended open without a date.', quote: 'Reach out when you are ready.', rep: 'Ava', spoke: 'closer', call_id: 'call-verified', highlight_id: 'highlight-2' }] };
const SERIES = { buckets: [{ label: 'Sep 7' }, { label: 'Sep 14' }], reps: [{ user_id: 'rep-1', name: 'Ava', handle: [{ rate: 35, handled: 7, total: 20 }, { rate: 42, handled: 10, total: 24 }], close: [{ rate: 20, closed: 4, total: 20 }, { rate: 25, closed: 6, total: 24 }], price: [{ value: 18, total: 20 }, { value: 21, total: 24 }] }], team: { handle: [{ rate: 35, reps_counted: 1, numerator: 7, total: 20 }, { rate: 42, reps_counted: 1, numerator: 10, total: 24 }], close: [{ rate: 20, reps_counted: 1, numerator: 4, total: 20 }, { rate: 25, reps_counted: 1, numerator: 6, total: 24 }], price: [{ value: 18, reps_counted: 1, total: 20 }, { value: 21, reps_counted: 1, total: 24 }] } };
const AVERAGE_REPS = [{ closing: { numerator: 11, total: 39 }, objections: { numerator: 14, total: 39 }, calltime: { seconds: 49.4 * 60 * 39, calls: 39 } }, { closing: { numerator: 7, total: 33 }, objections: { numerator: 11, total: 33 }, calltime: { seconds: 42 * 60 * 33, calls: 33 } }];
const AVERAGES = { metrics: Object.fromEntries(TEAM_AVERAGES.METRIC_ORDER.map((key) => { const metric = TEAM_AVERAGES.METRICS[key]; const pooled = key === 'calltime' ? TEAM_AVERAGES.poolDuration(AVERAGE_REPS) : TEAM_AVERAGES.poolRate(AVERAGE_REPS, key); return [key, { key, label: metric.label, target: metric.target, scale: metric.scale, unit: metric.unit, value: pooled.value, numerator: pooled.numerator, total: pooled.total, enough: pooled.enough, reason: pooled.reason, unit_name: metric.unitName, numerator_name: metric.numeratorName, direction: metric.direction, target_caption: metric.targetCaption, band: TEAM_AVERAGES.band(pooled.value, metric.target, metric.direction, metric.band), sweet_spot: metric.band ? { good: metric.band.good, ok: metric.band.ok } : null }]; })) };

const OVERVIEW_ANALYTICS = { calls: { analyzed: 12, total_in_range: 12, processing: 0, error: 0 }, avg_score: { mean: 72, graded_calls: 12, win_mean: 78, win_n: 5, other_mean: 68, other_n: 7 }, objections: { calls_with_objection: 4, total_highlights: 9 }, cash_collected: 0, prospect_close_rate: 23, prospect_close_wins: 23, prospect_close_total: 101, close_rate: 50, close_wins: 5, close_decided: 10, sections: { intro: { avg: 75, n: 10 }, discovery: { avg: 68, n: 10 }, pitch: { avg: 73, n: 10 }, objection: { avg: 66, n: 10 }, close: { avg: 78, n: 10 } }, weakest_section: 'objection', strongest_section: 'close', latest_one_things: [] };
const OVERVIEW_NEEDS_WORK = { available: true, state: 'gap', bucket: { handled: 4, total: 12, rate_pct: 33, baseline_pct: 58 }, detail: { buckets: [{ key: 'fear', label: 'Fear', handled: 4, total: 12, rate_pct: 33 }], context: { disqualifications: 1, logistical: 2 } }, card_text: 'Isolate the objection before answering it.' };
const OVERVIEW_SECTION_RANK = { sections: [{ section: 'objection', label: 'Objection Handling', score: 66, n: 10, enough: true, levelWithNext: false, gapToNext: 4, nextLabel: 'Discovery', rank_label: 'Lowest section', moments: [{ speaker: 'PROSPECT', quote: 'I want to make sure this will work for my team before I commit to the next step.', timestamp_seconds: 92, observation: 'The concern was left unexplored.', coaching: 'Ask one clarifying question before responding.', who: 'Ava', call_id: 'call-1', clip_url: 'https://fathom.video/calls/call-1?t=92' }, { speaker: 'CLOSER', quote: 'That makes sense. Let me understand what would need to be true for you.', timestamp_seconds: 101, observation: 'The closer began to isolate the concern.', coaching: 'Keep the question open before explaining the offer.', who: 'Ava', call_id: 'call-1', clip_url: 'https://fathom.video/calls/call-1?t=101' }] }] };

function render(stateOverrides) {
  let markup = '';
  const mounted = {};
  const content = { get innerHTML() { return markup; }, set innerHTML(value) { markup = String(value); }, insertAdjacentHTML(_position, value) { markup += String(value); } };
  const document = { getElementById: (id) => id === 'content' ? content : (mounted[id] ? { id, getContext: () => ({ id }) } : null), querySelector: () => null, querySelectorAll: (selector) => selector === '.rep-graph-slot' ? [...markup.matchAll(/data-canvas="([^"]+)"/g)].map((match) => ({ getAttribute: () => match[1], appendChild() { mounted[match[1]] = true; } })) : [], addEventListener() {}, createElement: () => ({ style: {}, classList: { add() {}, remove() {} }, appendChild() {} }), body: { appendChild() {}, classList: { add() {}, remove() {} }, dataset: {} }, documentElement: { style: {} } };
  const Chart = function Chart() { this.destroy = () => {}; };
  const window = { Chart, location: { hash: '', search: '', pathname: '/dashboard', href: 'https://fixture.test/dashboard', replace() {} }, localStorage: { getItem: () => null, setItem() {}, removeItem() {} }, addEventListener() {}, setTimeout() {}, clearTimeout() {}, setInterval() {}, clearInterval() {}, fetch: () => new Promise(() => {}), matchMedia: () => ({ matches: false, addEventListener() {} }), ScoutAuth: null, history: { replaceState() {} } };
  const api = new Function('document', 'window', 'Chart', 'localStorage', 'fetch', 'console', SCRIPT + '\nreturn { state, renderTeamSurface, renderOverview };')(document, window, Chart, window.localStorage, window.fetch, { log() {}, warn() {}, error() {} });
  Object.assign(api.state, stateOverrides); if (stateOverrides.view === 'overview') api.renderOverview(false); else api.renderTeamSurface(); return markup;
}

function base(view) { const coaching = view === 'team-coaching'; return { view, teamContext: { teams: [], rep_count: 3 }, teamContextLoading: false, teamOverview: { reps: [], per_rep: PERFORMANCE_REPS, totals: { avg_score: 72 } }, teamOverviewLoading: false, teamAverages: AVERAGES, teamAveragesLoading: false, teamRepSeries: SERIES, teamRepSeriesLoading: false, teamRecs: coaching ? TEAM_RECS : { available: true, working: [], improve: [] }, teamRecsLoading: false, teamCoachable: { reps: coaching ? [COACHING_REP, { ...COACHING_REP, user_id: 'rep-2', name: 'Drew', calls: 0, period_summary: { status: 'no_calls', from: '2026-09-01T00:00:00.000Z', to: '2026-09-30T23:59:59.999Z', patterns: [], coaching: { state: 'none' } } }] : [] }, teamCoachableLoading: false, teamNeedsWork: { available: false }, teamNeedsWorkLoading: false, teamDigest: { available: false }, teamDigestLoading: false, teamDetailMetric: null, teamObjectionCategory: '', teamRanges: {}, teamRangeInit: {} }; }
function overviewBase(overrides) { return Object.assign({ view: 'overview', me: { user_id: 'rep-1', role: 'manager' }, viewingUserId: 'rep-1', dateRange: { from: '2026-09-01T00:00:00.000Z', to: '2026-09-30T23:59:59.999Z' }, analytics2: OVERVIEW_ANALYTICS, analytics2Loading: false, gradingBacklog: { graded: 12, waiting: 0, total: 12 }, needsWork: OVERVIEW_NEEDS_WORK, needsWorkLoading: false, sectionRank: OVERVIEW_SECTION_RANK, sectionRankLoading: false, fathomStatus: { connected: true, last_sync_status: 'ok' }, zoomStatus: { connected: false }, repGraph: null, repGraphLoading: false, overviewExpanded: { coach: false, perf: false, recent: false } }, overrides || {}); }
function chromeFor(view) { const links = '<a class="workspace-team-link' + (view === 'team-performance' ? ' is-current' : '') + '">Performance</a><a class="workspace-team-link' + (view === 'team-coaching' ? ' is-current' : '') + '">Coaching</a>'; const overview = view === 'overview' ? CHROME.replace('class="nav-link" id="navOverview"', 'class="nav-link nav-active" id="navOverview"') : CHROME; return overview.replace('id="navTeamSep" style="display:none"', 'id="navTeamSep"').replace('id="navTeamWrap" style="display:none"', 'id="navTeamWrap"').replace('<nav class="workspace-team-pages" id="workspaceTeamPages" aria-label="Team pages"></nav>', '<nav class="workspace-team-pages" id="workspaceTeamPages" aria-label="Team pages">' + links + '</nav>'); }
function documentFor(view, overrides) { const state = view === 'overview' ? overviewBase(overrides) : base(view); return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>' + STYLE + '</style></head><body data-view="' + view + '">' + chromeFor(view) + '<div id="content">' + render(state) + '</div></main></body></html>'; }
const NO_CALL_ANALYTICS = Object.assign({}, OVERVIEW_ANALYTICS, { prospect_close_rate: null, prospect_close_wins: 0, prospect_close_total: 0, calls: { analyzed: 0, total_in_range: 0, processing: 0, error: 0 }, avg_score: { mean: null, graded_calls: 0, win_mean: null, win_n: 0, other_mean: null, other_n: 0 }, close_rate: null, close_wins: 0, close_decided: 0, sections: {}, weakest_section: null, strongest_section: null });
function writeFixtures(directory) { fs.mkdirSync(directory, { recursive: true }); for (const view of ['team-performance', 'team-coaching']) fs.writeFileSync(path.join(directory, view + '.html'), documentFor(view)); fs.writeFileSync(path.join(directory, 'overview-populated.html'), documentFor('overview')); fs.writeFileSync(path.join(directory, 'overview-loading.html'), documentFor('overview', { analytics2: null, analytics2Loading: true, gradingBacklog: null, needsWork: null, needsWorkLoading: true, sectionRank: null, sectionRankLoading: true })); fs.writeFileSync(path.join(directory, 'overview-no-calls.html'), documentFor('overview', { analytics2: NO_CALL_ANALYTICS, gradingBacklog: { graded: 0, waiting: 0, total: 0 }, needsWork: { available: false, reason: 'No analyzed calls in this range.' }, sectionRank: { sections: [] } })); return directory; }

if (require.main === module) process.stdout.write(writeFixtures(process.argv[2] || path.join(WEB, '__qa-observatory')) + '\n');
module.exports = { documentFor, writeFixtures };
