// Daily manager digest (v1.4 final stage): one short synthesized read-out per
// user-with-assigned-reps, covering their team's PREVIOUS ET calendar day.
// Generated by the sync cron (fire-and-forget after the sync-all loop) and by
// the owner-only manual trigger POST /team/digest/run. In-dashboard only.
//
// Follows lib/team-synthesis.js discipline exactly:
//   • cached in objection_synthesis_cache, synthesis_type='digest', keyed
//     (manager user_id, from_ts=digestDate@00:00Z, to_ts=nextDate@00:00Z,
//     analysis_set_hash) — from_ts matches what the /team/digest read route's
//     eq('from_ts', 'YYYY-MM-DD') casts to, and the set-hash folds in kbHash so
//     re-analyses AND KB changes invalidate automatically. Cache hit = no
//     Claude call → idempotent cron re-runs for the same day are free.
//   • credit-tolerant: an Anthropic failure returns {available:false, reason}
//     and is NOT cached, so the next cron pass retries. Failures never throw
//     out of generateDailyDigests' per-manager loop.
//   • zero-call days produce a deterministic "quiet day" digest with NO Claude
//     call — still cached, still renderable, never an error.
//
// "Yesterday" is the previous America/New_York calendar day (the team sells in
// ET). DST-safe via Intl — no timezone dependency. The cache KEY uses the date
// string at UTC midnight (read-route convention); the call_date QUERY WINDOW
// uses the real ET day bounds in UTC (04:00Z summer / 05:00Z winter).

const { isDisqualified } = require('./dq-exclusion');
const crypto = require('crypto');
const { displayNameFromEmail } = require('./display-name');
const Anthropic = require('@anthropic-ai/sdk');
const { CLAUDE_MODEL } = require('../config');
const { fetchSellingContext, SYNTHESIS_CATEGORIES } = require('./selling-context');
const { loadTeamWindow, cacheGet, cachePut } = require('./team-synthesis');
const { membersByManager } = require('./team-membership');

const { clipHref } = require('./clip-link');
const DIGEST_MAX_TOKENS = 1200;

var _anthropic = null;
function getAnthropic() {
  if (_anthropic) return _anthropic;
  if (!process.env.ANTHROPIC_API_KEY) throw new Error('Anthropic not configured — missing ANTHROPIC_API_KEY (set in Railway Variables).');
  _anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  return _anthropic;
}

// ─── ET calendar helpers (pure; DST-safe via Intl) ──────────────────────────
var _etFmt = null;
function etParts(d) {
  if (!_etFmt) {
    _etFmt = new Intl.DateTimeFormat('en-CA', {
      timeZone: 'America/New_York', hour12: false,
      year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit',
    });
  }
  var out = {};
  _etFmt.formatToParts(d).forEach(function (p) { out[p.type] = p.value; });
  // Intl may render midnight as '24' with hour12:false — normalize to 0.
  var hour = parseInt(out.hour, 10); if (hour === 24) hour = 0;
  return { date: out.year + '-' + out.month + '-' + out.day, hour: hour };
}
function etDateOf(now) { return etParts(now).date; }
function prevDateStr(dateStr) {
  var p = dateStr.split('-').map(Number);
  return new Date(Date.UTC(p[0], p[1] - 1, p[2]) - 86400000).toISOString().slice(0, 10);
}
function nextDateStr(dateStr) {
  var p = dateStr.split('-').map(Number);
  return new Date(Date.UTC(p[0], p[1] - 1, p[2]) + 86400000).toISOString().slice(0, 10);
}
function etYesterday(now) { return prevDateStr(etDateOf(now)); }
// UTC instant of ET midnight for a date. Guess EST (05:00Z); if ET is on DST
// that instant reads as 01:00 ET, so step back an hour. Handles both
// transition days: spring-forward midnight is EST (guess), fall-back is EDT (alt).
function etMidnightUtcMs(dateStr) {
  var p = dateStr.split('-').map(Number);
  var guess = Date.UTC(p[0], p[1] - 1, p[2], 5, 0, 0);
  var g = etParts(new Date(guess));
  if (g.date === dateStr && g.hour === 0) return guess;
  return guess - 3600000;
}
function etDayBoundsUtc(dateStr) {
  return {
    fromIso: new Date(etMidnightUtcMs(dateStr)).toISOString(),
    toIso: new Date(etMidnightUtcMs(nextDateStr(dateStr))).toISOString(),
  };
}
// Cache-key convention — MUST stay aligned with routes/team.js /team/digest,
// whose eq('from_ts', 'YYYY-MM-DD') casts to midnight UTC.
function digestCacheKey(dateStr) {
  return { fromTs: dateStr + 'T00:00:00.000Z', toTs: nextDateStr(dateStr) + 'T00:00:00.000Z' };
}
// Unlike the other lanes, the digest hash folds in the CALL id set too, not
// just analyses: a day whose calls have synced but not yet analyzed must not
// hash-collide with a true zero-call day, or a cached quiet digest would pin
// until the analyses landed.
/* ⚠⚠ THE PROMPT VERSION IS IN THE KEY, AND IT IS LOAD-BEARING — NOT BOOKKEEPING.
   A digest is generated once per day and CACHED. The compliance suppression is a
   PROMPT change, so without this every digest already in the cache — including
   the one that made a legal matter the day's focus — would keep rendering
   exactly as before, indefinitely. The fix would look shipped and change nothing
   on screen. Same failure the needs-work lane already paid for once, where the
   bucket labels lived inside the cached payload.
   ⚠ Bumping this invalidates cached digests so they regenerate under the new
   prompt. That is the intent, not a side effect. */
var DIGEST_PROMPT_VERSION = 'v2-2026-08-29-compliance-suppression';

function digestSetHash(analyses, kbHash, callIds) {
  return crypto.createHash('md5')
    .update((analyses || []).map(function (a) { return a.fathom_call_id + ':' + a.analyzed_at; }).sort().join('|')
      + '||calls:' + (callIds || []).slice().sort().join(',')
      + '||kb:' + kbHash
      + '||prompt:' + DIGEST_PROMPT_VERSION)
    .digest('hex');
}

function str(x, cap) { return (typeof x === 'string' && x.trim()) ? x.trim().slice(0, cap || 500) : null; }
// ⚠ delegates to lib/clip-link.js — the ONE place a deep link is built.
// Building it here would mean labelling it here, and this module does not
// know the provider. Pinned by test/clip-link-single-source.test.js.
function clipUrl(rec, ts) { return clipHref(rec, ts); }
function extractJson(text) {
  if (!text) return null;
  var cleaned = String(text).replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim();
  try { return JSON.parse(cleaned); } catch (_) {}
  var start = cleaned.indexOf('{');
  if (start === -1) return null;
  var depth = 0, inStr = false, esc = false;
  for (var i = start; i < cleaned.length; i++) {
    var ch = cleaned[i];
    if (esc) { esc = false; continue; }
    if (ch === '\\' && inStr) { esc = true; continue; }
    if (ch === '"') { inStr = !inStr; continue; }
    if (inStr) continue;
    if (ch === '{') depth++;
    else if (ch === '}') { depth--; if (depth === 0) { try { return JSON.parse(cleaned.slice(start, i + 1)); } catch (_) { return null; } } }
  }
  return null;
}

function quietDigest(dateStr) {
  return {
    date: dateStr,
    quiet: true,
    stats: { calls: 0, closed: 0, follow_up: 0, lost: 0, no_show: 0, reps_active: 0 },
    summary: 'Quiet day — no team calls were recorded on ' + dateStr + '.',
    notable: [],
    focus: 'No calls to review. A good day to check pipeline coverage and confirm the team’s calendars are filling.',
    generated_at: new Date().toISOString(),
  };
}

// ─── The digest itself ──────────────────────────────────────────────────────
// Returns {available, cached?, ...digest} — same envelope family as the other
// synthesis lanes. NEVER throws for content reasons; only unexpected DB errors
// propagate (caller catches per-manager).
async function computeDailyDigest(admin, keyId, repIds, dateStr, emailMap, nameMap) {
  var key = digestCacheKey(dateStr);
  var bounds = etDayBoundsUtc(dateStr);

  if (!repIds || repIds.length === 0) {
    return { available: false, reason: 'No assigned reps.' };
  }

  var w = await loadTeamWindow(admin, repIds, bounds.fromIso, bounds.toIso);
  var analyses = w.callIds.length === 0 ? [] : await w.inChunks('call_analyses',
    'fathom_call_id, analyzed_at, outcome, overall_score, one_thing, why_outcome, status',
    function (q) { return q.eq('status', 'done'); });

  // KB folded into the hash (and the prompt) — same discipline as the other lanes.
  var selling = await fetchSellingContext(admin, keyId, 2000, SYNTHESIS_CATEGORIES);
  var hash = digestSetHash(analyses, selling.kbHash, w.callIds);

  var cached = await cacheGet(admin, keyId, 'digest', key.fromTs, key.toTs, hash);
  if (cached) return Object.assign({ available: true, cached: true }, cached);

  // Zero calls → deterministic quiet digest, cached, no Claude spend.
  if (w.callIds.length === 0) {
    var q = quietDigest(dateStr);
    await cachePut(admin, keyId, 'digest', key.fromTs, key.toTs, hash, q);
    return Object.assign({ available: true, cached: false }, q);
  }

  // ── Facts (computed in JS — the model narrates, it does not count) ────────
  var repName = function (uid) {
    return (nameMap && nameMap[uid]) || (emailMap && emailMap[uid] ? displayNameFromEmail(emailMap[uid], 'rep') : 'rep');
  };
  var byOutcome = { closed: 0, follow_up: 0, lost: 0, no_show: 0 };
  var activeReps = {};
  var callLines = [];
  var analysisByCall = {};
  analyses.forEach(function (a) { analysisByCall[a.fathom_call_id] = a; });
  w.callIds.forEach(function (cid) {
    var c = w.meta[cid];
    activeReps[c.user_id] = true;
    var a = analysisByCall[cid];
    if (a && a.outcome && byOutcome.hasOwnProperty(a.outcome)) byOutcome[a.outcome]++;
    callLines.push('- [' + cid + '] ' + repName(c.user_id) + ' — "' + (c.title || 'untitled') + '"'
      + (a ? (' | outcome: ' + (a.outcome || 'unknown') + ' | score: ' + (a.overall_score == null ? 'n/a' : a.overall_score)
        + (a.why_outcome ? ' | why: ' + str(a.why_outcome, 200) : '')
        + (a.one_thing ? ' | one_thing: ' + str(a.one_thing, 200) : ''))
        : ' | not yet analyzed'));
  });

  var objectionsAll = await w.inChunks('call_highlights',
    'fathom_call_id, timestamp_seconds, speaker, quote, observation, type, objection_category, resolution',
    function (q) { return q.eq('type', 'objection');
  /* ⚠ A DQ CALL'S OBJECTIONS DO NOT REACH THE DIGEST'S FIGURES. Its prospect was
     never closeable, so counting them would put a rate in front of a manager
     that marks a rep down for a call that could not be won. The call itself is
     still analysed and still appears everywhere a COUNT is shown. */
  var dqDigest = {};
  (analyses || []).forEach(function (a2) { if (isDisqualified(a2)) dqDigest[a2.fathom_call_id] = 1; });
  var objections = objectionsAll.filter(function (r) { return !dqDigest[r.fathom_call_id]; });
 });
  var objLines = objections.slice(0, 20).map(function (h) {
    return '- [' + h.fathom_call_id + ' @' + h.timestamp_seconds + 's] ' + (h.objection_category || 'uncategorized')
      + ' / ' + (h.resolution || 'unknown') + ': "' + str(h.quote, 150) + '"';
  });

  var stats = {
    calls: w.callIds.length,
    closed: byOutcome.closed, follow_up: byOutcome.follow_up,
    lost: byOutcome.lost, no_show: byOutcome.no_show,
    reps_active: Object.keys(activeReps).length,
  };

  var promptLines = [
    'You are a sales team coach writing a manager’s morning digest for ' + dateStr + ' (yesterday).',
    'Facts below are computed from the database — do NOT restate every number; the dashboard already shows the stat chips. Your job is the READ of the day: what actually happened, what it means, and what to do about it today.',
    '',
    'TEAM STATS (already displayed — reference, don’t enumerate): ' + JSON.stringify(stats),
    '',
    'CALLS:',
  ].concat(callLines, [
    '',
    'OBJECTIONS RAISED:',
  ]).concat(objLines.length ? objLines : ['- none recorded'], [
    '',
  ]);
  if (selling.contextText && selling.contextText.trim()) {
    promptLines = promptLines.concat([
      'SELLING CONTEXT (this team’s offer and approach — ground your coaching in it):',
      selling.contextText.trim(),
      '',
    ]);
  }
  promptLines = promptLines.concat([
    'Respond with ONLY a JSON object:',
    '{',
    '  "summary": "2-3 sentences. The story of the day — factual, specific, film-coach tone. No cheerleading, no generic filler.",',
    '  "notable": [ { "call_id": "<id from CALLS>", "timestamp_seconds": <int or null>, "text": "one specific notable moment, pattern, or risk — cite the rep by the name used above" } ],  // 0-3 items, only genuinely notable ones',
    '  "focus": "ONE clear coaching focus for the team today — the single highest-leverage thing, specific enough to act on this morning. If one rep needs it most, say who."',
    '}',
    'Rules: every claim must trace to the facts above. call_id values MUST be copied from the CALLS list. If nothing is genuinely notable, return "notable": [].',
    /* ⚠⚠⚠ JUSTIN'S RULING 2026-08-28 — SUPPRESS. SCOUT DOES NOT SURFACE LEGAL OR
       LIABILITY MATTERS ANYWHERE: not as coaching, not as a notable moment, not
       as the day's focus, and NOT on some other surface either. The open
       question ("suppress entirely, or show it away from coaching?") is CLOSED
       and the answer is suppress. DO NOT BUILD A SECOND SURFACE FOR IT.

       ⚠ THE INCIDENT THIS EXISTS FOR: a rep told a prospect to overstate income
       on a financing application, and the digest made it TODAY'S FOCUS. Scout
       has zero context on liability and must never base coaching on it — and
       this failed in the most expensive way available, by rendering as an
       INSIGHT rather than as a wrong number. A manager acting on it coaches the
       wrong thing.

       ⚠ SUPPRESSION IS AT SELECTION, NOT AT DISPLAY. The moment must never be
       CHOSEN as notable or as the focus; filtering it after the model has built
       the day around it would leave the summary and the focus still shaped by
       it, with the evidence quietly missing — worse than including it, because
       the reasoning would no longer be checkable. */
    '',
    'EXCLUSION — legal, compliance and liability matters:',
    'Scout does not coach on legal or liability questions and has no context to judge them. If a moment involves a possible legal, regulatory or compliance problem — misrepresenting income or assets on an application, advising someone to state something untrue to a lender or insurer, or anything of that kind — DO NOT select it as a notable moment and DO NOT make it the focus, however significant it seems. Choose the next most useful SALES coaching point instead, and do not allude to the excluded moment in the summary.',
    'If excluding it leaves nothing genuinely notable, return "notable": [] — an empty list is the correct answer, not a reason to reach for it.',
  ]);

  var synthesis;
  try {
    var resp = await getAnthropic().messages.create({
      model: CLAUDE_MODEL, max_tokens: DIGEST_MAX_TOKENS,
      messages: [{ role: 'user', content: promptLines.join('\n') }],
    });
    var parsed = extractJson(resp.content && resp.content[0] ? resp.content[0].text : '');
    if (!parsed || !str(parsed.summary, 1000)) {
      // ⚠ CUSTOMER-FACING: no internal mechanism named.
      return { available: false, reason: 'Today\'s summary is not ready yet — it will appear shortly.' };
    }
    // Resolve notable entries against REAL rows only (never LLM-invented links).
    var notable = [];
    (Array.isArray(parsed.notable) ? parsed.notable.slice(0, 3) : []).forEach(function (n) {
      var text = str(n && n.text, 400);
      if (!text) return;
      var c = n && w.meta[n.call_id] ? w.meta[n.call_id] : null;
      var ts = (n && typeof n.timestamp_seconds === 'number' && n.timestamp_seconds >= 0) ? Math.floor(n.timestamp_seconds) : null;
      notable.push({
        text: text,
        rep: c ? repName(c.user_id) : null,
        call_title: c ? (c.title || null) : null,
        clip: c ? clipUrl(c.recording_url, ts) : null,
      });
    });
    synthesis = {
      date: dateStr,
      quiet: false,
      stats: stats,
      summary: str(parsed.summary, 1000),
      notable: notable,
      focus: str(parsed.focus, 600) || 'Review yesterday’s calls with the team.',
      generated_at: new Date().toISOString(),
    };
  } catch (e) {
    return { available: false, reason: 'Anthropic API failure' + ((e && e.status) ? ' (HTTP ' + e.status + ')' : '') + ': ' + ((e && e.message) || 'unknown') };
  }

  await cachePut(admin, keyId, 'digest', key.fromTs, key.toTs, hash, synthesis);
  return Object.assign({ available: true, cached: false }, synthesis);
}

// ─── Cron entry: one digest per user-with-reps ──────────────────────────────
// Never throws; returns a summary. Per-manager failures are caught + logged —
// the same degrade-gracefully rule as KB (a digest problem must never fail or
// block the sync cron that hosts it).
async function generateDailyDigests(admin, opts) {
  var dateStr = (opts && opts.date && /^\d{4}-\d{2}-\d{2}$/.test(opts.date)) ? opts.date : etYesterday(new Date());
  var summary = { date: dateStr, managers: 0, generated: 0, cached: 0, quiet: 0, unavailable: 0, errors: 0 };
  try {
    var profs = await admin.from('user_profiles').select('user_id, managed_by, first_name, last_name');
    if (profs.error) throw new Error('user_profiles: ' + profs.error.message);
    /* ⚠⚠ THE MANAGER IS ON THEIR OWN TEAM. This used to build the list from
       `managed_by` alone, which CANNOT contain the manager — so Josh's own calls
       were excluded from his own digest and it rendered "quiet day · 0 calls" for
       2026-08-24, a day he took EIGHT real calls (his four reps are three demo
       accounts and a test user, none with real calls). Ninth site of the defect
       `9a27979` fixed at eight endpoints; it never reached here because this runs
       from the cron with no `req` and so cannot call resolveTeam. The shared rule
       lives in lib/team-membership.js — do NOT re-add the manager inline. */
    var nameMap = {};
    (profs.data || []).forEach(function (p) {
      var n = [p.first_name, p.last_name].filter(Boolean).join(' ').trim();
      if (n) nameMap[p.user_id] = n;
    });
    var repsByManager = membersByManager(profs.data || []);
    var managerIds = Object.keys(repsByManager); // has-reps, NOT role — owner-with-reps included
    summary.managers = managerIds.length;
    if (managerIds.length === 0) return summary;

    var emailMap = {};
    try {
      var list = await admin.auth.admin.listUsers({ page: 1, perPage: 1000 });
      ((list.data && list.data.users) || []).forEach(function (u) { if (u && u.id) emailMap[u.id] = u.email || null; });
    } catch (e) { console.warn('[team-digest] emailMap failed (names degrade): ' + (e.message || 'unknown')); }

    for (var i = 0; i < managerIds.length; i++) {
      var keyId = managerIds[i];
      try {
        var d = await computeDailyDigest(admin, keyId, repsByManager[keyId], dateStr, emailMap, nameMap);
        if (!d.available) { summary.unavailable++; console.warn('[team-digest] unavailable for ' + keyId + ' (' + dateStr + '): ' + (d.reason || 'unknown')); }
        else if (d.cached) summary.cached++;
        else { summary.generated++; if (d.quiet) summary.quiet++; }
      } catch (perErr) {
        summary.errors++;
        console.error('[team-digest] failed for ' + keyId + ' (' + dateStr + '): ' + (perErr.message || 'unknown'));
      }
    }
  } catch (outerErr) {
    summary.errors++;
    console.error('[team-digest] generation pass failed (' + dateStr + '): ' + (outerErr.message || 'unknown'));
  }
  console.log('[team-digest] pass done: ' + JSON.stringify(summary));
  return summary;
}

module.exports = {
  computeDailyDigest: computeDailyDigest,
  generateDailyDigests: generateDailyDigests,
  etYesterday: etYesterday,   // used by routes/team.js for the default digest date
  etDateOf: etDateOf,         // used by routes/eod.js — one ET convention platform-wide
  etDayBoundsUtc: etDayBoundsUtc,
  // pure helpers exported for tests (underscore = test-only surface)
  _etDateOf: etDateOf,
  _etYesterday: etYesterday,
  _etDayBoundsUtc: etDayBoundsUtc,
  _digestCacheKey: digestCacheKey,
  _digestSetHash: digestSetHash,
  _quietDigest: quietDigest,
};
